version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
      # - "127.0.0.1:8080:8080"
    volumes: 
      - ./nginx/conf:/etc/nginx/conf.d
    #   - ./nginx-logs:/var/log/nginx

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    command:
      - -nginx.scrape-uri
      - http://nginx:8080/stub_status

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - nginx-exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus



